name: Build and Release ReMakeplace Updater

on:
  push:
    branches: [main, master]
    tags: ["v*"]
  pull_request:
    branches: [main, master]

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build standalone executable
        run: |
          python build.py

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ReMakeplaceUpdater-${{ github.sha }}
          path: release/

      - name: Create release and upload assets
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          name: ReMakeplace Updater ${{ github.ref_name }}
          body: |
            ## ReMakeplace Auto-Updater ${{ github.ref_name }}

            **🎉 Standalone Executable - No Python Required!**

            This is a completely self-contained executable that runs on any Windows system without needing Python installed.

            **What's New:**
            - Auto-update functionality for ReMakeplace
            - Modern MMO-style launcher interface
            - Smart caching system to avoid re-downloads
            - Multi-method extraction (supports BCJ2 filters)
            - Installation path configuration with validation

            **Download & Install:**
            1. Download `ReMakeplaceUpdater.exe` below
            2. Run the executable (no installation needed!)
            3. Browse to your ReMakeplace installation folder
            4. Click "Save & Continue"
            5. Enjoy automatic updates!

            **Requirements:**
            - Windows 10/11 (no Python needed!)
            - For advanced 7z formats: Install [7-Zip](https://www.7-zip.org/)

            **For Friends & Distribution:**
            - Just send them the `ReMakeplaceUpdater.exe` file
            - No additional setup or dependencies required
            - Works on any Windows computer

            ---

            **Package Contents:**
            - `ReMakeplaceUpdater.exe` - **Main executable (download this!)**
            - `config.json` - Configuration template
            - `README.md` - Full documentation
            - `launch_updater.bat` - Alternative launcher
          draft: false
          prerelease: false
          files: |
            release/ReMakeplaceUpdater.exe
            release/config.json
            release/README.md
            release/launch_updater.bat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
