name: Build and Release ReMakeplace Updater

on:
  push:
    branches: [main, master]
    tags: ["v*"]
  pull_request:
    branches: [main, master]

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build standalone executable
        run: |
          python build.py

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ReMakeplaceUpdater-${{ github.sha }}
          path: release/

      - name: Create release and upload assets
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          name: ReMakeplace Updater ${{ github.ref_name }}
          body: |
            ## ReMakeplace Auto-Updater ${{ github.ref_name }}

            **Package Contents:**
            - `ReMakeplaceUpdater.exe` - **Main executable (download this!)**
            - `config.json` - Configuration template
            - `README.md` - Full documentation
            - `launch_updater.bat` - Alternative launcher
          draft: false
          prerelease: false
          files: |
            release/ReMakeplaceUpdater.exe
            release/config.json
            release/README.md
            release/launch_updater.bat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
