name: Build and Release ReMakeplace Updater

on:
  push:
    branches: [main, master]
    tags: ["v*"]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest" # for Intel based macs.
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
          cache-dependency-path: "./ReMakeplaceUpdater/package-lock.json"

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./ReMakeplaceUpdater/src-tauri -> target"

      - name: Install frontend dependencies
        working-directory: ./ReMakeplaceUpdater
        run: npm ci

      - name: Build Tauri app and create release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: "./ReMakeplaceUpdater"
          tagName: remakeplace-updater-v__VERSION__
          releaseName: "ReMakeplace Updater v__VERSION__"
          releaseBody: |
            ## ReMakeplace Auto-Updater v__VERSION__

            A modern, native auto-updater for ReMakeplace built with Tauri.

            ### 🚀 Features
            - **Data Preservation**: Automatically preserves Custom and Save folders
            - **Modern UI**: Clean, responsive interface with dark theme

            ### 📦 Installation Options

            **Installers (Recommended for most users):**
            - **Windows**: `.msi` (Windows Installer) or `.exe` (NSIS Setup)
            - **macOS**: `.dmg` (Disk Image)
            - **Linux**: `.deb` (Debian/Ubuntu), `.rpm` (RedHat/Fedora), or `.AppImage` (Universal)

            **Portable Executables (Advanced users):**
            - **Windows**: `remakeplaceupdater.exe` (Portable - no installation required)
            - **macOS**: `remakeplaceupdater` (Portable binary)
            - **Linux**: `remakeplaceupdater` (Portable binary)

            ### 🔧 Setup
            1. Download the appropriate file for your operating system
            2. **Installers**: Run the installer and follow the setup wizard
            3. **Portable**: Extract (if needed) and run directly - no installation required
            4. Launch and configure your ReMakeplace installation path

          releaseDraft: ${{ !startsWith(github.ref, 'refs/tags/v') }}
          prerelease: false
          args: ${{ matrix.args }}
          includeUpdaterJson: false

      - name: Debug GitHub ref
        shell: bash
        run: |
          echo "GitHub ref: ${{ github.ref }}"
          echo "GitHub event name: ${{ github.event_name }}"
          echo "Is tag: ${{ startsWith(github.ref, 'refs/tags/') }}"

      - name: Create portable executable
        continue-on-error: true
        shell: bash
        run: |
          # Determine the target directory and executable name based on platform
          if [[ "${{ matrix.platform }}" == "windows-latest" ]]; then
            EXECUTABLE_NAME="remakeplaceupdater.exe"
            TARGET_DIR="target/release"
            PORTABLE_NAME="remakeplaceupdater-portable-windows.exe"
          elif [[ "${{ matrix.platform }}" == "ubuntu-22.04" ]]; then
            EXECUTABLE_NAME="remakeplaceupdater"
            TARGET_DIR="target/release"
            PORTABLE_NAME="remakeplaceupdater-portable-linux"
          elif [[ "${{ matrix.platform }}" == "macos-latest" ]]; then
            if [[ "${{ matrix.args }}" == *"aarch64"* ]]; then
              EXECUTABLE_NAME="remakeplaceupdater"
              TARGET_DIR="target/aarch64-apple-darwin/release"
              PORTABLE_NAME="remakeplaceupdater-portable-macos-aarch64"
            else
              EXECUTABLE_NAME="remakeplaceupdater"
              TARGET_DIR="target/x86_64-apple-darwin/release"
              PORTABLE_NAME="remakeplaceupdater-portable-macos-x64"
            fi
          fi

          # Change to the project directory
          cd ReMakeplaceUpdater

          echo "Looking for executable: $TARGET_DIR/$EXECUTABLE_NAME"
          echo "Current directory: $(pwd)"
          echo "Contents of target directory:"
          ls -la "$TARGET_DIR/" || echo "Target directory $TARGET_DIR does not exist"

          # Check if the executable exists
          if [[ -f "$TARGET_DIR/$EXECUTABLE_NAME" ]]; then
            echo "✅ Found portable executable at $TARGET_DIR/$EXECUTABLE_NAME"
            
            # Copy the executable with a descriptive name
            cp "$TARGET_DIR/$EXECUTABLE_NAME" "$PORTABLE_NAME"
            
            echo "✅ Portable executable created: $PORTABLE_NAME"
            echo "📁 File size: $(ls -lh "$PORTABLE_NAME" | awk '{print $5}' 2>/dev/null || stat -c%s "$PORTABLE_NAME" 2>/dev/null || echo 'unknown')"
            
            # Set output for artifact upload
            echo "PORTABLE_EXECUTABLE=$PORTABLE_NAME" >> $GITHUB_ENV
            echo "HAS_PORTABLE=true" >> $GITHUB_ENV
          else
            echo "⚠️ Portable executable not found at $TARGET_DIR/$EXECUTABLE_NAME"
            echo "This is expected for some platforms. Skipping portable creation."
            echo "HAS_PORTABLE=false" >> $GITHUB_ENV
          fi

      - name: Upload portable executable as artifact
        if: env.HAS_PORTABLE == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: portable-${{ matrix.platform }}-${{ matrix.args || 'default' }}
          path: ReMakeplaceUpdater/${{ env.PORTABLE_EXECUTABLE }}
          retention-days: 30

      - name: Upload portable executable to release
        if: startsWith(github.ref, 'refs/tags/') && env.HAS_PORTABLE == 'true'
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          cd ReMakeplaceUpdater

          # Get the tag name
          TAG_NAME=${GITHUB_REF#refs/tags/}

          echo "Attempting to upload portable executable to release: $TAG_NAME"

          # Wait a bit for the release to be created by tauri-action
          sleep 10

          # Upload the portable executable to the release
          if gh release upload "$TAG_NAME" "${{ env.PORTABLE_EXECUTABLE }}" --clobber; then
            echo "✅ Successfully uploaded portable executable to release"
          else
            echo "❌ Failed to upload portable executable to release"
            echo "The portable executable is still available as a workflow artifact"
          fi
